[package]
name = "mc-light-client-relayer"
version = "1.3.0-pre0"
authors = ["MobileCoin"]
edition = "2021"

[[bin]]
name = "light-client-relayer"
path = "src/bin/main.rs"

[dependencies]
mc-account-keys = { path = "../../account-keys" }
mc-blockchain-types = { path = "../../blockchain/types" }
mc-common = { path = "../../common", features = ["loggers"] }
mc-ledger-db = { path = "../../ledger/db" }
mc-transaction-core = { path = "../../transaction/core" }
mc-util-cli = { path = "../../util/cli" }
mc-util-grpc = { path = "../../util/grpc" }
mc-util-telemetry = { path = "../../util/telemetry" }
mc-util-uri = { path = "../../util/uri" }
mc-watcher = { path = "../../watcher" }

clap = { version = "4.0", features = ["derive", "env"] }
displaydoc = "0.2"
rayon = "1.7"
serde = "1"
serde_json = "1"
